# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:year/:month/:title/
relative_permalinks: true

# Setup
title:            Tomblog
tagline:          Software engineer and mobile technology enthusiast
description:      Software engineer and mobile technology enthusiast
url:              http://blog.quist.de
baseurl:          

disqus:           tomquist
google_analytics: UA-20360156-3

author:
  name:           Tom Quist
  url:            https://twitter.com/tomqueue

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/tomquist/tomquist.github.io

gems:
- jekyll-redirect-from
- jekyll-sitemap

exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md